name: Secret Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Note
        run: |
          echo "GitHub native secret scanning is enabled for this repository."
          echo "Custom patterns must be configured in repository settings, not in workflow YAML."
